<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="dbup-postgresql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\Scripts\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratio.Application\Ratio.Application.csproj" />
    <ProjectReference Include="..\Ratio.Domain\Ratio.Domain.csproj" />
  </ItemGroup>

</Project>
