<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratio.Application\Ratio.Application.csproj" />
    <ProjectReference Include="..\Ratio.Domain\Ratio.Domain.csproj" />
  </ItemGroup>

</Project>
